# Generated by Django 5.2.11 on 2026-02-26 07:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patient_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('birth_date', models.DateField()),
                ('ssn_encrypted', models.TextField(blank=True, default='')),
                ('passport_encrypted', models.TextField(blank=True, default='')),
                ('raw_json', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Patient Record',
                'verbose_name_plural': 'Patient Records',
                'ordering': ['-created_at'],
            },
        ),
    ]
